package com.example.jobagapi.funcional;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Test;
import org.junit.Before;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class RegisterAsEmployeerThenloginThenLogoutTest {

    private WebDriver driver;
    private WebDriverWait wait;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/test/java/com/example/jobagapi/funcional/drivers/chromedriver-v101.exe");
        driver = new ChromeDriver();
        wait = new WebDriverWait(driver, Duration.ofSeconds(5).getSeconds());
    }

    @After
    public void tearDown() {
        driver.close();
        driver.quit();
    }

    @Test
    public void registerAsEmployeerThenloginThenLogout() throws InterruptedException {
        String email = UUID.randomUUID() + "@test.com";
        String password = "password";
        Random rnd = new Random();
        Long phone = (long) rnd.nextInt(999999999);
        driver.get("https://cute-lolly-d05dcb.netlify.app/");
        driver.manage().window().setSize(new Dimension(1246, 1040));
        {
            WebElement element = driver.findElement(By.cssSelector(".btn-registrarse > .mat-button-wrapper"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".btn-registrarse > .mat-button-wrapper")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".but:nth-child(4) .mat-button-wrapper"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".mat-card:nth-child(5) > div > button")).click();
        driver.findElement(By.id("mat-input-2")).click();
        driver.findElement(By.id("mat-input-2")).sendKeys("test");
        driver.findElement(By.id("mat-input-3")).sendKeys("test");
        driver.findElement(By.id("mat-input-4")).sendKeys("22");
        driver.findElement(By.id("mat-input-5")).sendKeys(phone.toString());
        driver.findElement(By.id("mat-input-6")).sendKeys("test");
        driver.findElement(By.id("mat-input-7")).sendKeys(email);
        driver.findElement(By.id("mat-input-8")).sendKeys(password); // password
        driver.findElement(By.cssSelector(".mat-focus-indicator")).click();
        wait.until(d -> d.findElement(By.id("mat-input-9")));
        driver.findElement(By.id("mat-input-9")).click();
        driver.findElement(By.id("mat-input-9")).sendKeys(email);
        {
            WebElement element = driver.findElement(By.cssSelector(".btn-ingresar > .mat-button-wrapper"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.id("mat-input-9")).click();
        driver.findElement(By.id("mat-input-10")).sendKeys(password);
        driver.manage().timeouts().implicitlyWait(1, TimeUnit.SECONDS);
        driver.findElement(By.cssSelector(".btn-ingresar > .mat-button-wrapper")).click();
        wait.until(d -> d.findElement(By.cssSelector(".user-logout > .mat-button-wrapper")));
        {
            WebElement element = driver.findElement(By.cssSelector(".user-logout > .mat-button-wrapper"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".user-logout > .mat-button-wrapper")).click();
    }
}
